--SELECT rating, COUNT(*) AS film_count FROM film GROUP BY rating;
--SELECT replacement_cost, COUNT(*) AS film_count FROM film GROUP BY replacement_cost HAVING COUNT(*) > 50;
--SELECT store_id, COUNT(*) AS customer_count FROM customer GROUP BY store_id;
