--SELECT AVG(rental_rate) AS average_rental_rate FROM film;
--SELECT COUNT(*) AS film_count FROM film WHERE title LIKE 'C%';
--SELECT MAX(length) AS max_length FROM film WHERE rental_rate = 0.99;
--SELECT COUNT(DISTINCT replacement_cost) AS unique_replacement_cost_count FROM film WHERE length > 150;
